name: ZeroDay Security
description: Security Researcher (?) and Eternal student of the hacker arts
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://zerodaysec.net'
google_analytics: 'UA-117211350-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'zerodaysec.net'
author:         'Jonathan "syr0x" Lima'
