name: ZeroDay Security
description: security stuffs written by an security researcher and CTF addict
meta_description: "Blogging about security and nice stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: http://zerodaysec.net/
domain_name: 'http://zerodaysec.net'
google_analytics: 'UA-117211350-1'
gems:
  - jekyll-asciinema
  - jekyll-paginate

# Details for the RSS feed generator
url:            'zerodaysec.net'
author:         'Jonathan "syr0x" Lima'
